FROM lstephen/jenkins
MAINTAINER Levi Stephen <levi.stephen@gmail.com>

RUN install-plugin.sh git
RUN install-plugin.sh git-client
RUN install-plugin.sh github-oauth
RUN install-plugin.sh github
RUN install-plugin.sh github-api

RUN install-plugin.sh greenballs

